export interface VocabWordSeed {
  word: string;
  partOfSpeech: string; // "noun"|"verb"|"adjective"|"adverb"|"phrasal verb"|"phrase"
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  topic?: string; // e.g. "travel","business","emotions","academic","technology"
  translationRu: string;
  translationUk: string;
  definitionEn: string;
  exampleSentence: string;
  synonyms: string[];
  antonyms: string[];
  phonetic?: string;
}

export const vocabWords: VocabWordSeed[] = [
  // ===== A1 (30 words) =====
  {
    word: 'house',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'home',
    translationRu: 'дом',
    translationUk: 'будинок',
    definitionEn: 'A building where people live.',
    exampleSentence: 'My house has three bedrooms.',
    synonyms: ['home'],
    antonyms: [],
    phonetic: '/haʊs/',
  },
  {
    word: 'eat',
    partOfSpeech: 'verb',
    level: 'A1',
    topic: 'food',
    translationRu: 'есть',
    translationUk: 'їсти',
    definitionEn: 'To put food in your mouth and swallow it.',
    exampleSentence: 'We eat breakfast at eight o\'clock.',
    synonyms: ['consume'],
    antonyms: [],
    phonetic: '/iːt/',
  },
  {
    word: 'drink',
    partOfSpeech: 'verb',
    level: 'A1',
    topic: 'food',
    translationRu: 'пить',
    translationUk: 'пити',
    definitionEn: 'To swallow liquid.',
    exampleSentence: 'I drink water every morning.',
    synonyms: [],
    antonyms: [],
    phonetic: '/drɪŋk/',
  },
  {
    word: 'big',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'descriptions',
    translationRu: 'большой',
    translationUk: 'великий',
    definitionEn: 'Large in size.',
    exampleSentence: 'They live in a big city.',
    synonyms: ['large'],
    antonyms: ['small'],
    phonetic: '/bɪɡ/',
  },
  {
    word: 'small',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'descriptions',
    translationRu: 'маленький',
    translationUk: 'маленький',
    definitionEn: 'Little in size.',
    exampleSentence: 'She has a small dog.',
    synonyms: ['little'],
    antonyms: ['big'],
    phonetic: '/smɔːl/',
  },
  {
    word: 'happy',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'emotions',
    translationRu: 'счастливый',
    translationUk: 'щасливий',
    definitionEn: 'Feeling or showing pleasure.',
    exampleSentence: 'I am happy to see you.',
    synonyms: ['glad'],
    antonyms: ['sad'],
    phonetic: '/ˈhæpi/',
  },
  {
    word: 'sad',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'emotions',
    translationRu: 'грустный',
    translationUk: 'сумний',
    definitionEn: 'Feeling unhappy.',
    exampleSentence: 'He was sad after the film.',
    synonyms: ['unhappy'],
    antonyms: ['happy'],
    phonetic: '/sæd/',
  },
  {
    word: 'friend',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'relationships',
    translationRu: 'друг',
    translationUk: 'друг',
    definitionEn: 'A person you know well and like.',
    exampleSentence: 'She is my best friend.',
    synonyms: ['pal'],
    antonyms: ['enemy'],
    phonetic: '/frend/',
  },
  {
    word: 'school',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'education',
    translationRu: 'школа',
    translationUk: 'школа',
    definitionEn: 'A place where children go to learn.',
    exampleSentence: 'My children walk to school.',
    synonyms: [],
    antonyms: [],
    phonetic: '/skuːl/',
  },
  {
    word: 'work',
    partOfSpeech: 'verb',
    level: 'A1',
    topic: 'jobs',
    translationRu: 'работать',
    translationUk: 'працювати',
    definitionEn: 'To do a job.',
    exampleSentence: 'I work in an office.',
    synonyms: [],
    antonyms: ['rest'],
    phonetic: '/wɜːrk/',
  },
  {
    word: 'book',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'objects',
    translationRu: 'книга',
    translationUk: 'книга',
    definitionEn: 'Pages with words that you read.',
    exampleSentence: 'I am reading a good book.',
    synonyms: [],
    antonyms: [],
    phonetic: '/bʊk/',
  },
  {
    word: 'water',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'food',
    translationRu: 'вода',
    translationUk: 'вода',
    definitionEn: 'A clear liquid that people drink.',
    exampleSentence: 'Can I have a glass of water?',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˈwɔːtər/',
  },
  {
    word: 'day',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'time',
    translationRu: 'день',
    translationUk: 'день',
    definitionEn: 'A period of twenty-four hours.',
    exampleSentence: 'Today is a beautiful day.',
    synonyms: [],
    antonyms: ['night'],
    phonetic: '/deɪ/',
  },
  {
    word: 'night',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'time',
    translationRu: 'ночь',
    translationUk: 'ніч',
    definitionEn: 'The time when it is dark.',
    exampleSentence: 'We watched the stars at night.',
    synonyms: [],
    antonyms: ['day'],
    phonetic: '/naɪt/',
  },
  {
    word: 'go',
    partOfSpeech: 'verb',
    level: 'A1',
    topic: 'movement',
    translationRu: 'идти, ехать',
    translationUk: 'йти, їхати',
    definitionEn: 'To move from one place to another.',
    exampleSentence: 'Let\'s go to the park.',
    synonyms: ['move'],
    antonyms: ['come', 'stay'],
    phonetic: '/ɡoʊ/',
  },
  {
    word: 'come',
    partOfSpeech: 'verb',
    level: 'A1',
    topic: 'movement',
    translationRu: 'приходить',
    translationUk: 'приходити',
    definitionEn: 'To move toward the speaker.',
    exampleSentence: 'Please come here.',
    synonyms: [],
    antonyms: ['go'],
    phonetic: '/kʌm/',
  },
  {
    word: 'like',
    partOfSpeech: 'verb',
    level: 'A1',
    topic: 'emotions',
    translationRu: 'нравиться',
    translationUk: 'подобатися',
    definitionEn: 'To enjoy or find something pleasant.',
    exampleSentence: 'I like ice cream.',
    synonyms: ['enjoy'],
    antonyms: ['dislike'],
    phonetic: '/laɪk/',
  },
  {
    word: 'name',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'personal',
    translationRu: 'имя',
    translationUk: "ім'я",
    definitionEn: 'What a person or thing is called.',
    exampleSentence: 'My name is Peter.',
    synonyms: [],
    antonyms: [],
    phonetic: '/neɪm/',
  },
  {
    word: 'family',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'relationships',
    translationRu: 'семья',
    translationUk: "сім'я",
    definitionEn: 'A group of parents and children.',
    exampleSentence: 'I love spending time with my family.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˈfæməli/',
  },
  {
    word: 'car',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'transport',
    translationRu: 'машина',
    translationUk: 'автомобіль',
    definitionEn: 'A vehicle with four wheels.',
    exampleSentence: 'We drove to the shop by car.',
    synonyms: ['automobile'],
    antonyms: [],
    phonetic: '/kɑːr/',
  },
  {
    word: 'red',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'colors',
    translationRu: 'красный',
    translationUk: 'червоний',
    definitionEn: 'The color of blood or a tomato.',
    exampleSentence: 'She bought a red dress.',
    synonyms: [],
    antonyms: [],
    phonetic: '/red/',
  },
  {
    word: 'cold',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'weather',
    translationRu: 'холодный',
    translationUk: 'холодний',
    definitionEn: 'Having a low temperature.',
    exampleSentence: 'It is very cold outside today.',
    synonyms: ['chilly'],
    antonyms: ['hot'],
    phonetic: '/koʊld/',
  },
  {
    word: 'hot',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'weather',
    translationRu: 'жаркий, горячий',
    translationUk: 'спекотний, гарячий',
    definitionEn: 'Having a high temperature.',
    exampleSentence: 'The soup is too hot to eat.',
    synonyms: ['warm'],
    antonyms: ['cold'],
    phonetic: '/hɑːt/',
  },
  {
    word: 'want',
    partOfSpeech: 'verb',
    level: 'A1',
    topic: 'daily life',
    translationRu: 'хотеть',
    translationUk: 'хотіти',
    definitionEn: 'To wish for something.',
    exampleSentence: 'I want a cup of tea.',
    synonyms: ['wish'],
    antonyms: [],
    phonetic: '/wɑːnt/',
  },
  {
    word: 'help',
    partOfSpeech: 'verb',
    level: 'A1',
    topic: 'daily life',
    translationRu: 'помогать',
    translationUk: 'допомагати',
    definitionEn: 'To make something easier for someone.',
    exampleSentence: 'Can you help me with this bag?',
    synonyms: ['assist'],
    antonyms: [],
    phonetic: '/help/',
  },
  {
    word: 'money',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'daily life',
    translationRu: 'деньги',
    translationUk: 'гроші',
    definitionEn: 'What you use to buy things.',
    exampleSentence: 'He doesn\'t have much money.',
    synonyms: ['cash'],
    antonyms: [],
    phonetic: '/ˈmʌni/',
  },
  {
    word: 'time',
    partOfSpeech: 'noun',
    level: 'A1',
    topic: 'daily life',
    translationRu: 'время',
    translationUk: 'час',
    definitionEn: 'The thing measured by a clock.',
    exampleSentence: 'What time is it?',
    synonyms: [],
    antonyms: [],
    phonetic: '/taɪm/',
  },
  {
    word: 'new',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'descriptions',
    translationRu: 'новый',
    translationUk: 'новий',
    definitionEn: 'Recently made or bought.',
    exampleSentence: 'I bought a new phone.',
    synonyms: [],
    antonyms: ['old'],
    phonetic: '/nuː/',
  },
  {
    word: 'old',
    partOfSpeech: 'adjective',
    level: 'A1',
    topic: 'descriptions',
    translationRu: 'старый',
    translationUk: 'старий',
    definitionEn: 'Having lived or existed for a long time.',
    exampleSentence: 'My grandfather is very old.',
    synonyms: [],
    antonyms: ['new', 'young'],
    phonetic: '/oʊld/',
  },
  {
    word: 'today',
    partOfSpeech: 'adverb',
    level: 'A1',
    topic: 'time',
    translationRu: 'сегодня',
    translationUk: 'сьогодні',
    definitionEn: 'On this day.',
    exampleSentence: 'Today is my birthday.',
    synonyms: [],
    antonyms: ['yesterday', 'tomorrow'],
    phonetic: '/təˈdeɪ/',
  },

  // ===== A2 (30 words) =====
  {
    word: 'weather',
    partOfSpeech: 'noun',
    level: 'A2',
    topic: 'weather',
    translationRu: 'погода',
    translationUk: 'погода',
    definitionEn: 'The condition of the sky and temperature outside.',
    exampleSentence: 'The weather is lovely today.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˈweðər/',
  },
  {
    word: 'journey',
    partOfSpeech: 'noun',
    level: 'A2',
    topic: 'travel',
    translationRu: 'путешествие, поездка',
    translationUk: 'подорож, поїздка',
    definitionEn: 'An act of traveling from one place to another.',
    exampleSentence: 'The journey to the coast took five hours.',
    synonyms: ['trip'],
    antonyms: [],
    phonetic: '/ˈdʒɜːrni/',
  },
  {
    word: 'cheap',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'shopping',
    translationRu: 'дешёвый',
    translationUk: 'дешевий',
    definitionEn: 'Low in price.',
    exampleSentence: 'These shoes were very cheap.',
    synonyms: ['inexpensive'],
    antonyms: ['expensive'],
    phonetic: '/tʃiːp/',
  },
  {
    word: 'expensive',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'shopping',
    translationRu: 'дорогой',
    translationUk: 'дорогий',
    definitionEn: 'Costing a lot of money.',
    exampleSentence: 'That restaurant is too expensive for us.',
    synonyms: ['costly'],
    antonyms: ['cheap'],
    phonetic: '/ɪkˈspensɪv/',
  },
  {
    word: 'borrow',
    partOfSpeech: 'verb',
    level: 'A2',
    topic: 'daily life',
    translationRu: 'одалживать (брать)',
    translationUk: 'позичати (брати)',
    definitionEn: 'To take something and return it later.',
    exampleSentence: 'Can I borrow your pen?',
    synonyms: [],
    antonyms: ['lend'],
    phonetic: '/ˈbɑːroʊ/',
  },
  {
    word: 'lend',
    partOfSpeech: 'verb',
    level: 'A2',
    topic: 'daily life',
    translationRu: 'одалживать (давать)',
    translationUk: 'позичати (давати)',
    definitionEn: 'To give something to someone for a short time.',
    exampleSentence: 'She lent me her umbrella.',
    synonyms: [],
    antonyms: ['borrow'],
    phonetic: '/lend/',
  },
  {
    word: 'nervous',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'emotions',
    translationRu: 'нервный, взволнованный',
    translationUk: 'нервовий, схвильований',
    definitionEn: 'Worried or afraid about something.',
    exampleSentence: 'I feel nervous before exams.',
    synonyms: ['anxious'],
    antonyms: ['calm'],
    phonetic: '/ˈnɜːrvəs/',
  },
  {
    word: 'exciting',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'emotions',
    translationRu: 'захватывающий',
    translationUk: 'захопливий',
    definitionEn: 'Causing great interest or enthusiasm.',
    exampleSentence: 'The film was really exciting.',
    synonyms: ['thrilling'],
    antonyms: ['boring'],
    phonetic: '/ɪkˈsaɪtɪŋ/',
  },
  {
    word: 'invite',
    partOfSpeech: 'verb',
    level: 'A2',
    topic: 'social',
    translationRu: 'приглашать',
    translationUk: 'запрошувати',
    definitionEn: 'To ask someone to come to an event.',
    exampleSentence: 'We invited all our friends to the party.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ɪnˈvaɪt/',
  },
  {
    word: 'suggest',
    partOfSpeech: 'verb',
    level: 'A2',
    topic: 'communication',
    translationRu: 'предлагать',
    translationUk: 'пропонувати',
    definitionEn: 'To put forward an idea for consideration.',
    exampleSentence: 'I suggest we leave early.',
    synonyms: ['propose'],
    antonyms: [],
    phonetic: '/səˈdʒest/',
  },
  {
    word: 'improve',
    partOfSpeech: 'verb',
    level: 'A2',
    topic: 'daily life',
    translationRu: 'улучшать',
    translationUk: 'покращувати',
    definitionEn: 'To make or become better.',
    exampleSentence: 'She wants to improve her English.',
    synonyms: [],
    antonyms: ['worsen'],
    phonetic: '/ɪmˈpruːv/',
  },
  {
    word: 'neighbor',
    partOfSpeech: 'noun',
    level: 'A2',
    topic: 'home',
    translationRu: 'сосед',
    translationUk: 'сусід',
    definitionEn: 'A person who lives near you.',
    exampleSentence: 'My neighbor is very friendly.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˈneɪbər/',
  },
  {
    word: 'crowded',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'travel',
    translationRu: 'переполненный',
    translationUk: 'переповнений',
    definitionEn: 'Full of people.',
    exampleSentence: 'The train was very crowded this morning.',
    synonyms: [],
    antonyms: ['empty'],
    phonetic: '/ˈkraʊdɪd/',
  },
  {
    word: 'comfortable',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'descriptions',
    translationRu: 'удобный',
    translationUk: 'зручний',
    definitionEn: 'Providing physical ease.',
    exampleSentence: 'This chair is very comfortable.',
    synonyms: [],
    antonyms: ['uncomfortable'],
    phonetic: '/ˈkʌmftərbəl/',
  },
  {
    word: 'arrive',
    partOfSpeech: 'verb',
    level: 'A2',
    topic: 'travel',
    translationRu: 'прибывать',
    translationUk: 'прибувати',
    definitionEn: 'To reach a place.',
    exampleSentence: 'We arrived at the hotel at noon.',
    synonyms: [],
    antonyms: ['leave', 'depart'],
    phonetic: '/əˈraɪv/',
  },
  {
    word: 'delicious',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'food',
    translationRu: 'вкусный',
    translationUk: 'смачний',
    definitionEn: 'Having a very pleasant taste.',
    exampleSentence: 'This cake is delicious.',
    synonyms: ['tasty'],
    antonyms: [],
    phonetic: '/dɪˈlɪʃəs/',
  },
  {
    word: 'boring',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'emotions',
    translationRu: 'скучный',
    translationUk: 'нудний',
    definitionEn: 'Not interesting.',
    exampleSentence: 'The lecture was really boring.',
    synonyms: ['dull'],
    antonyms: ['exciting'],
    phonetic: '/ˈbɔːrɪŋ/',
  },
  {
    word: 'decide',
    partOfSpeech: 'verb',
    level: 'A2',
    topic: 'daily life',
    translationRu: 'решать',
    translationUk: 'вирішувати',
    definitionEn: 'To make a choice about something.',
    exampleSentence: 'We decided to stay home.',
    synonyms: [],
    antonyms: [],
    phonetic: '/dɪˈsaɪd/',
  },
  {
    word: 'weekend',
    partOfSpeech: 'noun',
    level: 'A2',
    topic: 'time',
    translationRu: 'выходные',
    translationUk: 'вихідні',
    definitionEn: 'Saturday and Sunday.',
    exampleSentence: 'What are your plans for the weekend?',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˈwiːkend/',
  },
  {
    word: 'polite',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'personality',
    translationRu: 'вежливый',
    translationUk: 'ввічливий',
    definitionEn: 'Having good manners.',
    exampleSentence: 'The waiter was very polite.',
    synonyms: ['courteous'],
    antonyms: ['rude'],
    phonetic: '/pəˈlaɪt/',
  },
  {
    word: 'rude',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'personality',
    translationRu: 'грубый',
    translationUk: 'грубий',
    definitionEn: 'Not polite.',
    exampleSentence: 'It was rude of him to interrupt.',
    synonyms: [],
    antonyms: ['polite'],
    phonetic: '/ruːd/',
  },
  {
    word: 'nearby',
    partOfSpeech: 'adverb',
    level: 'A2',
    topic: 'places',
    translationRu: 'поблизости',
    translationUk: 'поблизу',
    definitionEn: 'Not far away.',
    exampleSentence: 'There is a good café nearby.',
    synonyms: ['close'],
    antonyms: ['far'],
    phonetic: '/ˈnɪrbaɪ/',
  },
  {
    word: 'match',
    partOfSpeech: 'noun',
    level: 'A2',
    topic: 'sports',
    translationRu: 'матч',
    translationUk: 'матч',
    definitionEn: 'A sports game between two teams or players.',
    exampleSentence: 'We watched the football match together.',
    synonyms: ['game'],
    antonyms: [],
    phonetic: '/mætʃ/',
  },
  {
    word: 'healthy',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'health',
    translationRu: 'здоровый',
    translationUk: 'здоровий',
    definitionEn: 'In good physical condition.',
    exampleSentence: 'He eats healthy food every day.',
    synonyms: [],
    antonyms: ['unhealthy'],
    phonetic: '/ˈhelθi/',
  },
  {
    word: 'illness',
    partOfSpeech: 'noun',
    level: 'A2',
    topic: 'health',
    translationRu: 'болезнь',
    translationUk: 'хвороба',
    definitionEn: 'A disease or period of poor health.',
    exampleSentence: 'She recovered quickly from her illness.',
    synonyms: ['sickness'],
    antonyms: ['health'],
    phonetic: '/ˈɪlnəs/',
  },
  {
    word: 'careful',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'personality',
    translationRu: 'осторожный',
    translationUk: 'обережний',
    definitionEn: 'Paying attention to avoid mistakes or danger.',
    exampleSentence: 'Be careful when you cross the street.',
    synonyms: [],
    antonyms: ['careless'],
    phonetic: '/ˈkerfəl/',
  },
  {
    word: 'trip',
    partOfSpeech: 'noun',
    level: 'A2',
    topic: 'travel',
    translationRu: 'поездка',
    translationUk: 'поїздка',
    definitionEn: 'A journey to a place and back.',
    exampleSentence: 'We are planning a trip to Italy.',
    synonyms: ['journey'],
    antonyms: [],
    phonetic: '/trɪp/',
  },
  {
    word: 'quiet',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'descriptions',
    translationRu: 'тихий',
    translationUk: 'тихий',
    definitionEn: 'Making little or no noise.',
    exampleSentence: 'The library is always quiet.',
    synonyms: ['silent'],
    antonyms: ['loud', 'noisy'],
    phonetic: '/ˈkwaɪət/',
  },
  {
    word: 'busy',
    partOfSpeech: 'adjective',
    level: 'A2',
    topic: 'daily life',
    translationRu: 'занятой',
    translationUk: 'зайнятий',
    definitionEn: 'Having a lot to do.',
    exampleSentence: 'I am very busy this week.',
    synonyms: [],
    antonyms: ['free'],
    phonetic: '/ˈbɪzi/',
  },
  {
    word: 'guess',
    partOfSpeech: 'verb',
    level: 'A2',
    topic: 'daily life',
    translationRu: 'угадывать',
    translationUk: 'вгадувати',
    definitionEn: 'To give an answer without being sure.',
    exampleSentence: 'Can you guess how old I am?',
    synonyms: [],
    antonyms: [],
    phonetic: '/ɡes/',
  },

  // ===== B1 (30 words) =====
  {
    word: 'achieve',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'academic',
    translationRu: 'достигать',
    translationUk: 'досягати',
    definitionEn: 'To successfully complete or reach a goal.',
    exampleSentence: 'She worked hard to achieve her dream.',
    synonyms: ['accomplish'],
    antonyms: ['fail'],
    phonetic: '/əˈtʃiːv/',
  },
  {
    word: 'postpone',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'daily life',
    translationRu: 'откладывать',
    translationUk: 'відкладати',
    definitionEn: 'To delay an event to a later time.',
    exampleSentence: 'We had to postpone the meeting.',
    synonyms: ['delay'],
    antonyms: [],
    phonetic: '/poʊˈspoʊn/',
  },
  {
    word: 'reliable',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'personality',
    translationRu: 'надёжный',
    translationUk: 'надійний',
    definitionEn: 'Able to be trusted.',
    exampleSentence: 'He is a very reliable friend.',
    synonyms: ['dependable'],
    antonyms: ['unreliable'],
    phonetic: '/rɪˈlaɪəbəl/',
  },
  {
    word: 'opportunity',
    partOfSpeech: 'noun',
    level: 'B1',
    topic: 'business',
    translationRu: 'возможность',
    translationUk: 'можливість',
    definitionEn: 'A chance to do something.',
    exampleSentence: 'This job is a great opportunity for her.',
    synonyms: ['chance'],
    antonyms: [],
    phonetic: '/ˌɑːpərˈtuːnəti/',
  },
  {
    word: 'reduce',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'business',
    translationRu: 'уменьшать, сокращать',
    translationUk: 'зменшувати, скорочувати',
    definitionEn: 'To make something smaller or less.',
    exampleSentence: 'The company wants to reduce its costs.',
    synonyms: ['decrease'],
    antonyms: ['increase'],
    phonetic: '/rɪˈduːs/',
  },
  {
    word: 'increase',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'business',
    translationRu: 'увеличивать',
    translationUk: 'збільшувати',
    definitionEn: 'To become or make larger.',
    exampleSentence: 'Prices increased last month.',
    synonyms: ['grow'],
    antonyms: ['decrease', 'reduce'],
    phonetic: '/ɪnˈkriːs/',
  },
  {
    word: 'confident',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'emotions',
    translationRu: 'уверенный',
    translationUk: 'впевнений',
    definitionEn: 'Feeling sure about your abilities.',
    exampleSentence: 'She felt confident before the interview.',
    synonyms: ['self-assured'],
    antonyms: ['insecure'],
    phonetic: '/ˈkɑːnfɪdənt/',
  },
  {
    word: 'launch',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'business',
    translationRu: 'запускать (продукт)',
    translationUk: 'запускати (продукт)',
    definitionEn: 'To introduce a new product to the market.',
    exampleSentence: 'The company will launch a new phone next month.',
    synonyms: ['introduce'],
    antonyms: [],
    phonetic: '/lɔːntʃ/',
  },
  {
    word: 'environment',
    partOfSpeech: 'noun',
    level: 'B1',
    topic: 'nature',
    translationRu: 'окружающая среда',
    translationUk: 'навколишнє середовище',
    definitionEn: 'The natural world around us.',
    exampleSentence: 'We must protect the environment.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ɪnˈvaɪrənmənt/',
  },
  {
    word: 'competition',
    partOfSpeech: 'noun',
    level: 'B1',
    topic: 'business',
    translationRu: 'конкуренция',
    translationUk: 'конкуренція',
    definitionEn: 'A situation where people or companies compete.',
    exampleSentence: 'There is strong competition in this market.',
    synonyms: [],
    antonyms: ['cooperation'],
    phonetic: '/ˌkɑːmpəˈtɪʃən/',
  },
  {
    word: 'appreciate',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'emotions',
    translationRu: 'ценить',
    translationUk: 'цінувати',
    definitionEn: 'To be grateful for something.',
    exampleSentence: 'I really appreciate your help.',
    synonyms: [],
    antonyms: [],
    phonetic: '/əˈpriːʃieɪt/',
  },
  {
    word: 'complain',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'communication',
    translationRu: 'жаловаться',
    translationUk: 'скаржитися',
    definitionEn: 'To express dissatisfaction about something.',
    exampleSentence: 'He complained about the noisy neighbors.',
    synonyms: [],
    antonyms: ['praise'],
    phonetic: '/kəmˈpleɪn/',
  },
  {
    word: 'convenient',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'daily life',
    translationRu: 'удобный',
    translationUk: 'зручний',
    definitionEn: 'Suitable for your needs and plans.',
    exampleSentence: 'Is this time convenient for you?',
    synonyms: ['handy'],
    antonyms: ['inconvenient'],
    phonetic: '/kənˈviːniənt/',
  },
  {
    word: 'estimate',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'business',
    translationRu: 'оценивать (примерно)',
    translationUk: 'оцінювати (приблизно)',
    definitionEn: 'To roughly calculate a value or amount.',
    exampleSentence: 'They estimated the cost at two thousand dollars.',
    synonyms: ['calculate'],
    antonyms: [],
    phonetic: '/ˈestɪmeɪt/',
  },
  {
    word: 'ancient',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'history',
    translationRu: 'древний',
    translationUk: 'стародавній',
    definitionEn: 'Very old, from a long time ago.',
    exampleSentence: 'We visited an ancient castle.',
    synonyms: [],
    antonyms: ['modern'],
    phonetic: '/ˈeɪnʃənt/',
  },
  {
    word: 'device',
    partOfSpeech: 'noun',
    level: 'B1',
    topic: 'technology',
    translationRu: 'устройство',
    translationUk: 'пристрій',
    definitionEn: 'A piece of equipment made for a purpose.',
    exampleSentence: 'This device measures your heart rate.',
    synonyms: ['gadget'],
    antonyms: [],
    phonetic: '/dɪˈvaɪs/',
  },
  {
    word: 'permission',
    partOfSpeech: 'noun',
    level: 'B1',
    topic: 'daily life',
    translationRu: 'разрешение',
    translationUk: 'дозвіл',
    definitionEn: 'Consent or authorization to do something.',
    exampleSentence: 'You need permission to enter this area.',
    synonyms: [],
    antonyms: ['prohibition'],
    phonetic: '/pərˈmɪʃən/',
  },
  {
    word: 'responsible',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'personality',
    translationRu: 'ответственный',
    translationUk: 'відповідальний',
    definitionEn: 'Having a duty to deal with something.',
    exampleSentence: 'She is responsible for the whole project.',
    synonyms: [],
    antonyms: ['irresponsible'],
    phonetic: '/rɪˈspɑːnsəbəl/',
  },
  {
    word: 'imagine',
    partOfSpeech: 'verb',
    level: 'B1',
    topic: 'thinking',
    translationRu: 'воображать',
    translationUk: 'уявляти',
    definitionEn: 'To form a picture in your mind.',
    exampleSentence: 'Imagine living on a tropical island.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ɪˈmædʒɪn/',
  },
  {
    word: 'purpose',
    partOfSpeech: 'noun',
    level: 'B1',
    topic: 'academic',
    translationRu: 'цель',
    translationUk: 'мета',
    definitionEn: 'The reason for doing something.',
    exampleSentence: 'What is the purpose of this meeting?',
    synonyms: ['aim'],
    antonyms: [],
    phonetic: '/ˈpɜːrpəs/',
  },
  {
    word: 'stressful',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'emotions',
    translationRu: 'напряжённый, стрессовый',
    translationUk: 'напружений, стресовий',
    definitionEn: 'Causing mental or emotional strain.',
    exampleSentence: 'Her job is very stressful.',
    synonyms: [],
    antonyms: ['relaxing'],
    phonetic: '/ˈstresfəl/',
  },
  {
    word: 'ingredient',
    partOfSpeech: 'noun',
    level: 'B1',
    topic: 'food',
    translationRu: 'ингредиент',
    translationUk: 'інгредієнт',
    definitionEn: 'A food item used to make a dish.',
    exampleSentence: 'Flour is the main ingredient in bread.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ɪnˈɡriːdiənt/',
  },
  {
    word: 'strict',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'personality',
    translationRu: 'строгий',
    translationUk: 'суворий',
    definitionEn: 'Demanding that rules be followed.',
    exampleSentence: 'Our teacher is very strict about homework.',
    synonyms: [],
    antonyms: ['lenient'],
    phonetic: '/strɪkt/',
  },
  {
    word: 'available',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'daily life',
    translationRu: 'доступный',
    translationUk: 'доступний',
    definitionEn: 'Able to be used or obtained.',
    exampleSentence: 'Is this seat available?',
    synonyms: [],
    antonyms: ['unavailable'],
    phonetic: '/əˈveɪləbəl/',
  },
  {
    word: 'suitable',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'descriptions',
    translationRu: 'подходящий',
    translationUk: 'придатний',
    definitionEn: 'Right or appropriate for a purpose.',
    exampleSentence: 'This dress is not suitable for a job interview.',
    synonyms: ['appropriate'],
    antonyms: ['unsuitable'],
    phonetic: '/ˈsuːtəbəl/',
  },
  {
    word: 'give up',
    partOfSpeech: 'phrasal verb',
    level: 'B1',
    topic: 'daily life',
    translationRu: 'отказываться, бросать',
    translationUk: 'відмовлятися, кидати',
    definitionEn: 'To stop trying to do something.',
    exampleSentence: 'Don\'t give up on your dreams.',
    synonyms: ['quit'],
    antonyms: [],
  },
  {
    word: 'look forward to',
    partOfSpeech: 'phrasal verb',
    level: 'B1',
    topic: 'emotions',
    translationRu: 'с нетерпением ждать',
    translationUk: 'з нетерпінням чекати',
    definitionEn: 'To feel excited about something that will happen.',
    exampleSentence: 'I am looking forward to the holidays.',
    synonyms: [],
    antonyms: ['dread'],
  },
  {
    word: 'find out',
    partOfSpeech: 'phrasal verb',
    level: 'B1',
    topic: 'daily life',
    translationRu: 'узнавать',
    translationUk: 'дізнаватися',
    definitionEn: 'To discover information.',
    exampleSentence: 'I need to find out the train times.',
    synonyms: ['discover'],
    antonyms: [],
  },
  {
    word: 'run out of',
    partOfSpeech: 'phrasal verb',
    level: 'B1',
    topic: 'daily life',
    translationRu: 'заканчиваться (о запасах)',
    translationUk: 'закінчуватися (про запаси)',
    definitionEn: 'To have no more of something left.',
    exampleSentence: 'We ran out of milk this morning.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'get along',
    partOfSpeech: 'phrasal verb',
    level: 'B1',
    topic: 'relationships',
    translationRu: 'ладить',
    translationUk: 'ладнати',
    definitionEn: 'To have a good relationship with someone.',
    exampleSentence: 'She gets along well with her colleagues.',
    synonyms: [],
    antonyms: [],
  },

  // ===== B2 (30 words) =====
  {
    word: 'reluctant',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'emotions',
    translationRu: 'неохотный, нежелающий',
    translationUk: 'неохочий, небажаючий',
    definitionEn: 'Unwilling and hesitant.',
    exampleSentence: 'He was reluctant to sign the contract.',
    synonyms: ['unwilling'],
    antonyms: ['eager'],
    phonetic: '/rɪˈlʌktənt/',
  },
  {
    word: 'substantial',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'business',
    translationRu: 'значительный, существенный',
    translationUk: 'значний, суттєвий',
    definitionEn: 'Large in amount or importance.',
    exampleSentence: 'They made a substantial profit this year.',
    synonyms: ['considerable'],
    antonyms: ['negligible'],
    phonetic: '/səbˈstænʃəl/',
  },
  {
    word: 'overwhelm',
    partOfSpeech: 'verb',
    level: 'B2',
    topic: 'emotions',
    translationRu: 'подавлять, переполнять',
    translationUk: 'переповнювати, пригнічувати',
    definitionEn: 'To affect someone strongly with a feeling or amount.',
    exampleSentence: 'She was overwhelmed with joy.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˌoʊvərˈwelm/',
  },
  {
    word: 'simultaneous',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'academic',
    translationRu: 'одновременный',
    translationUk: 'одночасний',
    definitionEn: 'Happening at the same time.',
    exampleSentence: 'The two events were simultaneous.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˌsɪməlˈteɪniəs/',
  },
  {
    word: 'controversial',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'academic',
    translationRu: 'спорный, противоречивый',
    translationUk: 'суперечливий',
    definitionEn: 'Causing public disagreement.',
    exampleSentence: 'It was a controversial decision.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˌkɑːntrəˈvɜːrʃəl/',
  },
  {
    word: 'diverse',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'academic',
    translationRu: 'разнообразный',
    translationUk: 'різноманітний',
    definitionEn: 'Showing a great deal of variety.',
    exampleSentence: 'The city has a diverse population.',
    synonyms: ['varied'],
    antonyms: ['uniform'],
    phonetic: '/daɪˈvɜːrs/',
  },
  {
    word: 'assumption',
    partOfSpeech: 'noun',
    level: 'B2',
    topic: 'academic',
    translationRu: 'предположение',
    translationUk: 'припущення',
    definitionEn: 'Something believed to be true without proof.',
    exampleSentence: 'That is a dangerous assumption to make.',
    synonyms: [],
    antonyms: [],
    phonetic: '/əˈsʌmpʃən/',
  },
  {
    word: 'contribute',
    partOfSpeech: 'verb',
    level: 'B2',
    topic: 'business',
    translationRu: 'вносить вклад',
    translationUk: 'робити внесок',
    definitionEn: 'To give something in order to help.',
    exampleSentence: 'Everyone contributed ideas to the plan.',
    synonyms: [],
    antonyms: [],
    phonetic: '/kənˈtrɪbjuːt/',
  },
  {
    word: 'sustainable',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'environment',
    translationRu: 'устойчивый (экологически)',
    translationUk: 'сталий (екологічно)',
    definitionEn: 'Able to continue over a long period without harming resources.',
    exampleSentence: 'We need more sustainable energy sources.',
    synonyms: [],
    antonyms: [],
    phonetic: '/səˈsteɪnəbəl/',
  },
  {
    word: 'perspective',
    partOfSpeech: 'noun',
    level: 'B2',
    topic: 'academic',
    translationRu: 'точка зрения',
    translationUk: 'точка зору',
    definitionEn: 'A particular way of viewing something.',
    exampleSentence: 'Try to see it from her perspective.',
    synonyms: ['viewpoint'],
    antonyms: [],
    phonetic: '/pərˈspektɪv/',
  },
  {
    word: 'inevitable',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'academic',
    translationRu: 'неизбежный',
    translationUk: 'неминучий',
    definitionEn: 'Certain to happen; unavoidable.',
    exampleSentence: 'Change is inevitable in a growing business.',
    synonyms: ['unavoidable'],
    antonyms: ['avoidable'],
    phonetic: '/ɪnˈevɪtəbəl/',
  },
  {
    word: 'compromise',
    partOfSpeech: 'noun',
    level: 'B2',
    topic: 'relationships',
    translationRu: 'компромисс',
    translationUk: 'компроміс',
    definitionEn: 'An agreement reached by each side giving up something.',
    exampleSentence: 'They finally reached a compromise.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˈkɑːmprəmaɪz/',
  },
  {
    word: 'lay off',
    partOfSpeech: 'phrasal verb',
    level: 'B2',
    topic: 'business',
    translationRu: 'увольнять (по сокращению)',
    translationUk: 'звільняти (через скорочення)',
    definitionEn: 'To dismiss employees, usually due to lack of work.',
    exampleSentence: 'The factory laid off two hundred workers.',
    synonyms: ['dismiss'],
    antonyms: ['hire'],
  },
  {
    word: 'come across',
    partOfSpeech: 'phrasal verb',
    level: 'B2',
    topic: 'communication',
    translationRu: 'производить впечатление',
    translationUk: 'справляти враження',
    definitionEn: 'To give a particular impression.',
    exampleSentence: 'He comes across as very confident.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'put off',
    partOfSpeech: 'phrasal verb',
    level: 'B2',
    topic: 'daily life',
    translationRu: 'откладывать',
    translationUk: 'відкладати',
    definitionEn: 'To delay doing something.',
    exampleSentence: 'She keeps putting off her dentist appointment.',
    synonyms: ['postpone'],
    antonyms: [],
  },
  {
    word: 'thorough',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'academic',
    translationRu: 'тщательный',
    translationUk: 'ретельний',
    definitionEn: 'Complete and careful about every detail.',
    exampleSentence: 'The police conducted a thorough investigation.',
    synonyms: ['meticulous'],
    antonyms: ['careless'],
    phonetic: '/ˈθɜːroʊ/',
  },
  {
    word: 'accomplish',
    partOfSpeech: 'verb',
    level: 'B2',
    topic: 'business',
    translationRu: 'выполнять, достигать',
    translationUk: 'виконувати, досягати',
    definitionEn: 'To successfully finish a task.',
    exampleSentence: 'We accomplished all our goals this quarter.',
    synonyms: ['achieve'],
    antonyms: [],
    phonetic: '/əˈkɑːmplɪʃ/',
  },
  {
    word: 'anticipate',
    partOfSpeech: 'verb',
    level: 'B2',
    topic: 'thinking',
    translationRu: 'предвидеть, ожидать',
    translationUk: 'передбачати, очікувати',
    definitionEn: 'To expect something and prepare for it.',
    exampleSentence: 'We anticipate strong demand for this product.',
    synonyms: ['expect'],
    antonyms: [],
    phonetic: '/ænˈtɪsɪpeɪt/',
  },
  {
    word: 'vulnerable',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'emotions',
    translationRu: 'уязвимый',
    translationUk: 'вразливий',
    definitionEn: 'Easily hurt physically or emotionally.',
    exampleSentence: 'Elderly people are often vulnerable to scams.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˈvʌlnərəbəl/',
  },
  {
    word: 'genuine',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'descriptions',
    translationRu: 'настоящий, искренний',
    translationUk: 'справжній, щирий',
    definitionEn: 'Real and authentic, not fake.',
    exampleSentence: 'She showed genuine concern for his health.',
    synonyms: ['authentic'],
    antonyms: ['fake'],
    phonetic: '/ˈdʒenjuɪn/',
  },
  {
    word: 'consequence',
    partOfSpeech: 'noun',
    level: 'B2',
    topic: 'academic',
    translationRu: 'последствие',
    translationUk: 'наслідок',
    definitionEn: 'A result of an action or condition.',
    exampleSentence: 'Every choice has consequences.',
    synonyms: ['result'],
    antonyms: [],
    phonetic: '/ˈkɑːnsɪkwens/',
  },
  {
    word: 'motivate',
    partOfSpeech: 'verb',
    level: 'B2',
    topic: 'business',
    translationRu: 'мотивировать',
    translationUk: 'мотивувати',
    definitionEn: 'To give someone a reason to act.',
    exampleSentence: 'Good managers know how to motivate their teams.',
    synonyms: ['inspire'],
    antonyms: ['discourage'],
    phonetic: '/ˈmoʊtɪveɪt/',
  },
  {
    word: 'flexible',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'business',
    translationRu: 'гибкий',
    translationUk: 'гнучкий',
    definitionEn: 'Able to change or adapt easily.',
    exampleSentence: 'The company offers flexible working hours.',
    synonyms: [],
    antonyms: ['rigid'],
    phonetic: '/ˈfleksəbəl/',
  },
  {
    word: 'phenomenon',
    partOfSpeech: 'noun',
    level: 'B2',
    topic: 'academic',
    translationRu: 'явление',
    translationUk: 'явище',
    definitionEn: 'A fact or situation that is observed to exist.',
    exampleSentence: 'Climate change is a global phenomenon.',
    synonyms: [],
    antonyms: [],
    phonetic: '/fəˈnɑːmɪnən/',
  },
  {
    word: 'insight',
    partOfSpeech: 'noun',
    level: 'B2',
    topic: 'academic',
    translationRu: 'понимание, проницательность',
    translationUk: 'розуміння, проникливість',
    definitionEn: 'A clear understanding of something complex.',
    exampleSentence: 'The book offers real insight into human behavior.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ˈɪnsaɪt/',
  },
  {
    word: 'undermine',
    partOfSpeech: 'verb',
    level: 'B2',
    topic: 'academic',
    translationRu: 'подрывать',
    translationUk: 'підривати',
    definitionEn: 'To gradually weaken something.',
    exampleSentence: 'The scandal undermined public trust.',
    synonyms: ['weaken'],
    antonyms: ['strengthen'],
    phonetic: '/ˌʌndərˈmaɪn/',
  },
  {
    word: 'thrive',
    partOfSpeech: 'verb',
    level: 'B2',
    topic: 'business',
    translationRu: 'процветать',
    translationUk: 'процвітати',
    definitionEn: 'To grow or develop successfully.',
    exampleSentence: 'Small businesses thrive in this neighborhood.',
    synonyms: ['flourish'],
    antonyms: ['struggle'],
    phonetic: '/θraɪv/',
  },
  {
    word: 'legitimate',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'academic',
    translationRu: 'законный, обоснованный',
    translationUk: 'законний, обґрунтований',
    definitionEn: 'Reasonable and justified, or lawful.',
    exampleSentence: 'She raised a legitimate concern.',
    synonyms: ['valid'],
    antonyms: ['illegitimate'],
    phonetic: '/lɪˈdʒɪtɪmət/',
  },
  {
    word: 'ambiguous',
    partOfSpeech: 'adjective',
    level: 'B2',
    topic: 'academic',
    translationRu: 'неоднозначный',
    translationUk: 'неоднозначний',
    definitionEn: 'Having more than one possible meaning.',
    exampleSentence: 'The instructions were rather ambiguous.',
    synonyms: ['unclear'],
    antonyms: ['clear'],
    phonetic: '/æmˈbɪɡjuəs/',
  },
  {
    word: 'implement',
    partOfSpeech: 'verb',
    level: 'B2',
    topic: 'business',
    translationRu: 'внедрять, осуществлять',
    translationUk: 'впроваджувати, здійснювати',
    definitionEn: 'To put a plan or decision into effect.',
    exampleSentence: 'The company will implement new safety rules.',
    synonyms: ['execute'],
    antonyms: [],
    phonetic: '/ˈɪmplɪment/',
  },

  // ===== C1 (30 words) =====
  {
    word: 'meticulous',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'personality',
    translationRu: 'дотошный, скрупулёзный',
    translationUk: 'прискіпливий, скрупульозний',
    definitionEn: 'Showing great attention to detail; very careful.',
    exampleSentence: 'She is meticulous about her work.',
    synonyms: ['thorough'],
    antonyms: ['careless'],
    phonetic: '/məˈtɪkjələs/',
  },
  {
    word: 'ubiquitous',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'academic',
    translationRu: 'вездесущий',
    translationUk: 'всюдисущий',
    definitionEn: 'Present or found everywhere.',
    exampleSentence: 'Smartphones have become ubiquitous in modern life.',
    synonyms: ['omnipresent'],
    antonyms: ['rare'],
    phonetic: '/juːˈbɪkwɪtəs/',
  },
  {
    word: 'alleviate',
    partOfSpeech: 'verb',
    level: 'C1',
    topic: 'academic',
    translationRu: 'облегчать, смягчать',
    translationUk: 'полегшувати, пом\'якшувати',
    definitionEn: 'To make suffering or a problem less severe.',
    exampleSentence: 'The medicine helped alleviate her pain.',
    synonyms: ['ease'],
    antonyms: ['worsen'],
    phonetic: '/əˈliːvieɪt/',
  },
  {
    word: 'zeal',
    partOfSpeech: 'noun',
    level: 'C1',
    topic: 'emotions',
    translationRu: 'рвение, пыл',
    translationUk: 'запал, завзяття',
    definitionEn: 'Great energy and enthusiasm for a cause.',
    exampleSentence: 'He pursued his goals with great zeal.',
    synonyms: ['enthusiasm'],
    antonyms: ['apathy'],
    phonetic: '/ziːl/',
  },
  {
    word: 'discrepancy',
    partOfSpeech: 'noun',
    level: 'C1',
    topic: 'academic',
    translationRu: 'несоответствие, расхождение',
    translationUk: 'невідповідність, розбіжність',
    definitionEn: 'A difference between things that should match.',
    exampleSentence: 'There is a discrepancy between the two reports.',
    synonyms: ['inconsistency'],
    antonyms: [],
    phonetic: '/dɪˈskrepənsi/',
  },
  {
    word: 'inherent',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'academic',
    translationRu: 'присущий, врождённый',
    translationUk: 'притаманний, вроджений',
    definitionEn: 'Existing as a natural or basic part of something.',
    exampleSentence: 'There are inherent risks in any investment.',
    synonyms: ['intrinsic'],
    antonyms: ['extrinsic'],
    phonetic: '/ɪnˈhɪrənt/',
  },
  {
    word: 'discern',
    partOfSpeech: 'verb',
    level: 'C1',
    topic: 'thinking',
    translationRu: 'различать, распознавать',
    translationUk: 'розрізняти, розпізнавати',
    definitionEn: 'To recognize or notice something clearly.',
    exampleSentence: 'It was hard to discern any real difference.',
    synonyms: ['perceive'],
    antonyms: [],
    phonetic: '/dɪˈsɜːrn/',
  },
  {
    word: 'notion',
    partOfSpeech: 'noun',
    level: 'C1',
    topic: 'academic',
    translationRu: 'понятие, представление',
    translationUk: 'поняття, уявлення',
    definitionEn: 'A belief or idea about something.',
    exampleSentence: 'She rejected the notion that money brings happiness.',
    synonyms: ['concept'],
    antonyms: [],
    phonetic: '/ˈnoʊʃən/',
  },
  {
    word: 'plausible',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'academic',
    translationRu: 'правдоподобный',
    translationUk: 'правдоподібний',
    definitionEn: 'Seeming reasonable or probable.',
    exampleSentence: 'That is a plausible explanation.',
    synonyms: ['credible'],
    antonyms: ['implausible'],
    phonetic: '/ˈplɔːzəbəl/',
  },
  {
    word: 'reluctantly',
    partOfSpeech: 'adverb',
    level: 'C1',
    topic: 'emotions',
    translationRu: 'неохотно',
    translationUk: 'неохоче',
    definitionEn: 'In an unwilling manner.',
    exampleSentence: 'He reluctantly agreed to help.',
    synonyms: ['unwillingly'],
    antonyms: ['eagerly'],
    phonetic: '/rɪˈlʌktəntli/',
  },
  {
    word: 'coherent',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'academic',
    translationRu: 'связный, последовательный',
    translationUk: 'зв\'язний, послідовний',
    definitionEn: 'Logical and well-organized.',
    exampleSentence: 'She gave a coherent argument for the change.',
    synonyms: ['logical'],
    antonyms: ['incoherent'],
    phonetic: '/koʊˈhɪrənt/',
  },
  {
    word: 'pragmatic',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'personality',
    translationRu: 'прагматичный',
    translationUk: 'прагматичний',
    definitionEn: 'Dealing with things sensibly and practically.',
    exampleSentence: 'We need a pragmatic solution to this problem.',
    synonyms: ['practical'],
    antonyms: ['idealistic'],
    phonetic: '/præɡˈmætɪk/',
  },
  {
    word: 'skeptical',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'thinking',
    translationRu: 'скептический',
    translationUk: 'скептичний',
    definitionEn: 'Doubting the truth of something.',
    exampleSentence: 'I remain skeptical about his promises.',
    synonyms: ['doubtful'],
    antonyms: ['credulous'],
    phonetic: '/ˈskeptɪkəl/',
  },
  {
    word: 'nuance',
    partOfSpeech: 'noun',
    level: 'C1',
    topic: 'academic',
    translationRu: 'нюанс, тонкость',
    translationUk: 'нюанс, тонкість',
    definitionEn: 'A subtle difference in meaning or expression.',
    exampleSentence: 'A good translator captures every nuance.',
    synonyms: ['subtlety'],
    antonyms: [],
    phonetic: '/ˈnuːɑːns/',
  },
  {
    word: 'facilitate',
    partOfSpeech: 'verb',
    level: 'C1',
    topic: 'business',
    translationRu: 'способствовать, облегчать',
    translationUk: 'сприяти, полегшувати',
    definitionEn: 'To make an action or process easier.',
    exampleSentence: 'The new software facilitates communication between teams.',
    synonyms: ['enable'],
    antonyms: ['hinder'],
    phonetic: '/fəˈsɪlɪteɪt/',
  },
  {
    word: 'redundant',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'business',
    translationRu: 'избыточный; сокращённый (о работе)',
    translationUk: 'надлишковий; звільнений (з роботи)',
    definitionEn: 'No longer needed; superfluous.',
    exampleSentence: 'Several parts of the report were redundant.',
    synonyms: ['superfluous'],
    antonyms: ['essential'],
    phonetic: '/rɪˈdʌndənt/',
  },
  {
    word: 'candid',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'personality',
    translationRu: 'откровенный, прямой',
    translationUk: 'відвертий, прямий',
    definitionEn: 'Honest and direct, even about difficult topics.',
    exampleSentence: 'He gave a candid assessment of the situation.',
    synonyms: ['frank'],
    antonyms: ['evasive'],
    phonetic: '/ˈkændɪd/',
  },
  {
    word: 'deteriorate',
    partOfSpeech: 'verb',
    level: 'C1',
    topic: 'academic',
    translationRu: 'ухудшаться',
    translationUk: 'погіршуватися',
    definitionEn: 'To become progressively worse.',
    exampleSentence: 'Relations between the two countries deteriorated.',
    synonyms: ['worsen'],
    antonyms: ['improve'],
    phonetic: '/dɪˈtɪriəreɪt/',
  },
  {
    word: 'compelling',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'academic',
    translationRu: 'убедительный, захватывающий',
    translationUk: 'переконливий, захопливий',
    definitionEn: 'Very convincing or engaging.',
    exampleSentence: 'She made a compelling argument.',
    synonyms: ['persuasive'],
    antonyms: [],
    phonetic: '/kəmˈpelɪŋ/',
  },
  {
    word: 'resilient',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'personality',
    translationRu: 'стойкий, устойчивый',
    translationUk: 'стійкий',
    definitionEn: 'Able to recover quickly from difficulties.',
    exampleSentence: 'Children can be remarkably resilient.',
    synonyms: ['tough'],
    antonyms: ['fragile'],
    phonetic: '/rɪˈzɪliənt/',
  },
  {
    word: 'daunting',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'emotions',
    translationRu: 'пугающий, устрашающий',
    translationUk: 'лякаючий, страхітливий',
    definitionEn: 'Seeming difficult and intimidating.',
    exampleSentence: 'The task ahead seemed daunting.',
    synonyms: ['intimidating'],
    antonyms: ['reassuring'],
    phonetic: '/ˈdɔːntɪŋ/',
  },
  {
    word: 'sever',
    partOfSpeech: 'verb',
    level: 'C1',
    topic: 'academic',
    translationRu: 'разрывать (связи), отсекать',
    translationUk: 'розривати (зв\'язки), відтинати',
    definitionEn: 'To end a relationship or connection completely.',
    exampleSentence: 'The company severed ties with its old supplier.',
    synonyms: ['cut off'],
    antonyms: [],
    phonetic: '/ˈsevər/',
  },
  {
    word: 'distill',
    partOfSpeech: 'verb',
    level: 'C1',
    topic: 'thinking',
    translationRu: 'выделять суть, дистиллировать',
    translationUk: 'виокремлювати суть, дистилювати',
    definitionEn: 'To extract the essential meaning or most important parts.',
    exampleSentence: 'He distilled the report into three main points.',
    synonyms: [],
    antonyms: [],
    phonetic: '/dɪˈstɪl/',
  },
  {
    word: 'intricate',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'descriptions',
    translationRu: 'сложный, замысловатый',
    translationUk: 'складний, заплутаний',
    definitionEn: 'Very complicated or detailed.',
    exampleSentence: 'The watch has an intricate mechanism.',
    synonyms: ['complex'],
    antonyms: ['simple'],
    phonetic: '/ˈɪntrɪkət/',
  },
  {
    word: 'ambivalent',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'emotions',
    translationRu: 'двойственный, противоречивый',
    translationUk: 'двоїстий, суперечливий',
    definitionEn: 'Having mixed feelings about something.',
    exampleSentence: 'She felt ambivalent about moving abroad.',
    synonyms: ['conflicted'],
    antonyms: ['certain'],
    phonetic: '/æmˈbɪvələnt/',
  },
  {
    word: 'refute',
    partOfSpeech: 'verb',
    level: 'C1',
    topic: 'academic',
    translationRu: 'опровергать',
    translationUk: 'спростовувати',
    definitionEn: 'To prove that something is wrong or false.',
    exampleSentence: 'The scientist refuted the earlier theory.',
    synonyms: ['disprove'],
    antonyms: ['confirm'],
    phonetic: '/rɪˈfjuːt/',
  },
  {
    word: 'exacerbate',
    partOfSpeech: 'verb',
    level: 'C1',
    topic: 'academic',
    translationRu: 'усугублять',
    translationUk: 'загострювати, посилювати',
    definitionEn: 'To make a problem or situation worse.',
    exampleSentence: 'The delay only exacerbated the crisis.',
    synonyms: ['worsen'],
    antonyms: ['ease'],
    phonetic: '/ɪɡˈzæsərbeɪt/',
  },
  {
    word: 'tacit',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'academic',
    translationRu: 'молчаливый, подразумеваемый',
    translationUk: 'мовчазний, неявний',
    definitionEn: 'Understood without being directly stated.',
    exampleSentence: 'There was tacit agreement among the team.',
    synonyms: ['implicit'],
    antonyms: ['explicit'],
    phonetic: '/ˈtæsɪt/',
  },
  {
    word: 'unprecedented',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'academic',
    translationRu: 'беспрецедентный',
    translationUk: 'безпрецедентний',
    definitionEn: 'Never having happened before.',
    exampleSentence: 'The company saw unprecedented growth this year.',
    synonyms: [],
    antonyms: [],
    phonetic: '/ʌnˈpresɪdentɪd/',
  },
  {
    word: 'eloquent',
    partOfSpeech: 'adjective',
    level: 'C1',
    topic: 'communication',
    translationRu: 'красноречивый',
    translationUk: 'красномовний',
    definitionEn: 'Fluent and persuasive in speaking or writing.',
    exampleSentence: 'She gave an eloquent speech at the conference.',
    synonyms: ['articulate'],
    antonyms: ['inarticulate'],
    phonetic: '/ˈeləkwənt/',
  },

  // ===== C2 (30 words) =====
  {
    word: 'ephemeral',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'academic',
    translationRu: 'эфемерный, недолговечный',
    translationUk: 'ефемерний, недовговічний',
    definitionEn: 'Lasting for a very short time.',
    exampleSentence: 'Fame in this industry is often ephemeral.',
    synonyms: ['fleeting'],
    antonyms: ['permanent'],
    phonetic: '/ɪˈfemərəl/',
  },
  {
    word: 'obfuscate',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'academic',
    translationRu: 'запутывать, затуманивать',
    translationUk: 'заплутувати, затуманювати',
    definitionEn: 'To make something unclear or confusing on purpose.',
    exampleSentence: 'The report seemed designed to obfuscate the real issue.',
    synonyms: ['confuse'],
    antonyms: ['clarify'],
    phonetic: '/ˈɑːbfəskeɪt/',
  },
  {
    word: 'sycophantic',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'personality',
    translationRu: 'льстивый, подхалимский',
    translationUk: 'улесливий, підлабузницький',
    definitionEn: 'Excessively flattering toward someone important.',
    exampleSentence: 'His sycophantic comments annoyed his colleagues.',
    synonyms: ['fawning'],
    antonyms: [],
    phonetic: '/ˌsɪkəˈfæntɪk/',
  },
  {
    word: 'inscrutable',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'descriptions',
    translationRu: 'непостижимый, загадочный',
    translationUk: 'незбагненний, загадковий',
    definitionEn: 'Impossible to understand or interpret.',
    exampleSentence: 'Her expression remained inscrutable throughout the meeting.',
    synonyms: ['enigmatic'],
    antonyms: ['transparent'],
    phonetic: '/ɪnˈskruːtəbəl/',
  },
  {
    word: 'ostensibly',
    partOfSpeech: 'adverb',
    level: 'C2',
    topic: 'academic',
    translationRu: 'якобы, внешне',
    translationUk: 'нібито, зовні',
    definitionEn: 'As appears or is claimed on the surface, perhaps not truthfully.',
    exampleSentence: 'He left, ostensibly to make a phone call.',
    synonyms: ['apparently'],
    antonyms: [],
    phonetic: '/ɑːˈstensəbli/',
  },
  {
    word: 'vindicate',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'academic',
    translationRu: 'оправдывать, реабилитировать',
    translationUk: 'виправдовувати, реабілітувати',
    definitionEn: 'To prove that someone was right or justified.',
    exampleSentence: 'The results ultimately vindicated her theory.',
    synonyms: ['justify'],
    antonyms: ['condemn'],
    phonetic: '/ˈvɪndɪkeɪt/',
  },
  {
    word: 'capricious',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'personality',
    translationRu: 'капризный, непостоянный',
    translationUk: 'примхливий, непостійний',
    definitionEn: 'Given to sudden and unpredictable changes.',
    exampleSentence: 'The company\'s capricious policies frustrated employees.',
    synonyms: ['fickle'],
    antonyms: ['stable'],
    phonetic: '/kəˈprɪʃəs/',
  },
  {
    word: 'insidious',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'academic',
    translationRu: 'коварный, незаметно вредный',
    translationUk: 'підступний, непомітно шкідливий',
    definitionEn: 'Proceeding in a gradual, harmful way that is not obvious.',
    exampleSentence: 'The disease had an insidious onset.',
    synonyms: ['stealthy'],
    antonyms: [],
    phonetic: '/ɪnˈsɪdiəs/',
  },
  {
    word: 'pervasive',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'academic',
    translationRu: 'вездесущий, распространённый',
    translationUk: 'всепроникний, поширений',
    definitionEn: 'Spreading widely throughout an area or group.',
    exampleSentence: 'There is a pervasive sense of uncertainty in the market.',
    synonyms: ['widespread'],
    antonyms: [],
    phonetic: '/pərˈveɪsɪv/',
  },
  {
    word: 'equivocate',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'communication',
    translationRu: 'уклоняться от прямого ответа',
    translationUk: 'ухилятися від прямої відповіді',
    definitionEn: 'To use ambiguous language to avoid committing to a position.',
    exampleSentence: 'The politician equivocated when asked about the scandal.',
    synonyms: ['hedge'],
    antonyms: [],
    phonetic: '/ɪˈkwɪvəkeɪt/',
  },
  {
    word: 'juxtapose',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'academic',
    translationRu: 'сопоставлять, ставить рядом',
    translationUk: 'зіставляти, ставити поруч',
    definitionEn: 'To place two things side by side for comparison.',
    exampleSentence: 'The exhibition juxtaposes ancient and modern art.',
    synonyms: ['contrast'],
    antonyms: [],
    phonetic: '/ˈdʒʌkstəpoʊz/',
  },
  {
    word: 'quintessential',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'descriptions',
    translationRu: 'типичнейший, самый характерный',
    translationUk: 'типовий, найхарактерніший',
    definitionEn: 'Representing the most perfect or typical example of something.',
    exampleSentence: 'This dish is the quintessential comfort food.',
    synonyms: ['archetypal'],
    antonyms: [],
    phonetic: '/ˌkwɪntɪˈsenʃəl/',
  },
  {
    word: 'disparage',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'communication',
    translationRu: 'принижать, отзываться пренебрежительно',
    translationUk: 'принижувати, зневажливо відгукуватися',
    definitionEn: 'To speak of someone or something with disrespect.',
    exampleSentence: 'He often disparages his competitors in interviews.',
    synonyms: ['belittle'],
    antonyms: ['praise'],
    phonetic: '/dɪˈspærɪdʒ/',
  },
  {
    word: 'aloof',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'personality',
    translationRu: 'отчуждённый, держащийся особняком',
    translationUk: 'відсторонений, замкнений',
    definitionEn: 'Distant and not friendly or forthcoming.',
    exampleSentence: 'He remained aloof at the party, speaking to no one.',
    synonyms: ['distant'],
    antonyms: ['sociable'],
    phonetic: '/əˈluːf/',
  },
  {
    word: 'consolidate',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'business',
    translationRu: 'консолидировать, укреплять',
    translationUk: 'консолідувати, зміцнювати',
    definitionEn: 'To combine several things into one stronger whole.',
    exampleSentence: 'The two firms decided to consolidate their operations.',
    synonyms: ['merge'],
    antonyms: [],
    phonetic: '/kənˈsɑːlɪdeɪt/',
  },
  {
    word: 'circumvent',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'academic',
    translationRu: 'обходить (правила, препятствия)',
    translationUk: 'обходити (правила, перешкоди)',
    definitionEn: 'To find a way around an obstacle or rule.',
    exampleSentence: 'They found a loophole to circumvent the regulation.',
    synonyms: ['bypass'],
    antonyms: [],
    phonetic: '/ˌsɜːrkəmˈvent/',
  },
  {
    word: 'diligent',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'personality',
    translationRu: 'усердный, старательный',
    translationUk: 'старанний, ретельний',
    definitionEn: 'Showing careful and persistent effort in work.',
    exampleSentence: 'She is a diligent researcher who checks every source.',
    synonyms: ['industrious'],
    antonyms: ['lazy'],
    phonetic: '/ˈdɪlɪdʒənt/',
  },
  {
    word: 'placate',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'communication',
    translationRu: 'умиротворять, успокаивать',
    translationUk: 'заспокоювати, вгамовувати',
    definitionEn: 'To make someone less angry or upset.',
    exampleSentence: 'The manager tried to placate the frustrated customer.',
    synonyms: ['appease'],
    antonyms: ['provoke'],
    phonetic: '/ˈpleɪkeɪt/',
  },
  {
    word: 'protracted',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'academic',
    translationRu: 'затяжной, продолжительный',
    translationUk: 'затяжний, тривалий',
    definitionEn: 'Lasting for a long time, often longer than expected.',
    exampleSentence: 'The negotiations turned into a protracted dispute.',
    synonyms: ['prolonged'],
    antonyms: ['brief'],
    phonetic: '/proʊˈtræktɪd/',
  },
  {
    word: 'esoteric',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'academic',
    translationRu: 'эзотерический, малопонятный',
    translationUk: 'езотеричний, малозрозумілий',
    definitionEn: 'Understood by only a small, specialized group.',
    exampleSentence: 'The lecture covered some fairly esoteric topics.',
    synonyms: ['obscure'],
    antonyms: ['mainstream'],
    phonetic: '/ˌesəˈterɪk/',
  },
  {
    word: 'magnanimous',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'personality',
    translationRu: 'великодушный',
    translationUk: 'великодушний',
    definitionEn: 'Generous and forgiving, especially toward a rival.',
    exampleSentence: 'She was magnanimous in victory, praising her opponent.',
    synonyms: ['generous'],
    antonyms: ['petty'],
    phonetic: '/mæɡˈnænɪməs/',
  },
  {
    word: 'conundrum',
    partOfSpeech: 'noun',
    level: 'C2',
    topic: 'academic',
    translationRu: 'загадка, сложная проблема',
    translationUk: 'загадка, складна проблема',
    definitionEn: 'A confusing and difficult problem.',
    exampleSentence: 'Economists face a real conundrum over inflation policy.',
    synonyms: ['puzzle'],
    antonyms: [],
    phonetic: '/kəˈnʌndrəm/',
  },
  {
    word: 'ubiquity',
    partOfSpeech: 'noun',
    level: 'C2',
    topic: 'academic',
    translationRu: 'вездесущность',
    translationUk: 'всюдисущість',
    definitionEn: 'The state of being present everywhere.',
    exampleSentence: 'The ubiquity of smartphones has changed how we communicate.',
    synonyms: ['omnipresence'],
    antonyms: [],
    phonetic: '/juːˈbɪkwəti/',
  },
  {
    word: 'assuage',
    partOfSpeech: 'verb',
    level: 'C2',
    topic: 'emotions',
    translationRu: 'смягчать, унимать',
    translationUk: 'пом\'якшувати, вгамовувати',
    definitionEn: 'To make an unpleasant feeling less intense.',
    exampleSentence: 'His apology did little to assuage her anger.',
    synonyms: ['soothe'],
    antonyms: ['aggravate'],
    phonetic: '/əˈsweɪdʒ/',
  },
  {
    word: 'venerable',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'descriptions',
    translationRu: 'почтенный, уважаемый',
    translationUk: 'поважний, шановний',
    definitionEn: 'Respected because of age, wisdom, or achievement.',
    exampleSentence: 'The venerable professor had taught for fifty years.',
    synonyms: ['esteemed'],
    antonyms: [],
    phonetic: '/ˈvenərəbəl/',
  },
  {
    word: 'read between the lines',
    partOfSpeech: 'phrase',
    level: 'C2',
    topic: 'communication',
    translationRu: 'читать между строк',
    translationUk: 'читати між рядків',
    definitionEn: 'To understand a hidden meaning that is not directly stated.',
    exampleSentence: 'If you read between the lines, you can tell she is unhappy with the offer.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'beat around the bush',
    partOfSpeech: 'phrase',
    level: 'C2',
    topic: 'communication',
    translationRu: 'ходить вокруг да около',
    translationUk: 'ходити навколо та навкруги',
    definitionEn: 'To avoid talking about the main point directly.',
    exampleSentence: 'Stop beating around the bush and tell me what happened.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'a double-edged sword',
    partOfSpeech: 'phrase',
    level: 'C2',
    topic: 'idioms',
    translationRu: 'палка о двух концах',
    translationUk: 'палиця на два кінці',
    definitionEn: 'Something that has both positive and negative effects.',
    exampleSentence: 'Social media is a double-edged sword for small businesses.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'a blessing in disguise',
    partOfSpeech: 'phrase',
    level: 'C2',
    topic: 'idioms',
    translationRu: 'скрытое благо, не было бы счастья, да несчастье помогло',
    translationUk: 'приховане благо, не було б щастя, та нещастя допомогло',
    definitionEn: 'Something that seems bad at first but turns out to be beneficial.',
    exampleSentence: 'Losing that job turned out to be a blessing in disguise.',
    synonyms: [],
    antonyms: [],
  },
  {
    word: 'perfunctory',
    partOfSpeech: 'adjective',
    level: 'C2',
    topic: 'descriptions',
    translationRu: 'формальный, поверхностный',
    translationUk: 'формальний, поверховий',
    definitionEn: 'Carried out with minimal effort or interest, as a routine.',
    exampleSentence: 'He gave a perfunctory nod and continued reading.',
    synonyms: ['cursory'],
    antonyms: ['thorough'],
    phonetic: '/pərˈfʌŋktəri/',
  },
];
