import type { PlacementQuestion } from '../../core/placement-test/types.js';

export const placementQuestionBank: PlacementQuestion[] = [
  // ===== GRAMMAR =====
  // A1
  {
    id: 'gr-a1-01',
    level: 'A1',
    category: 'grammar',
    prompt: '___ you a student?',
    options: ['Is', 'Am', 'Are', 'Be'],
    correctIndex: 2,
  },
  {
    id: 'gr-a1-02',
    level: 'A1',
    category: 'grammar',
    prompt: 'She ___ to school every day.',
    options: ['go', 'goes', 'going', 'gone'],
    correctIndex: 1,
  },
  {
    id: 'gr-a1-03',
    level: 'A1',
    category: 'grammar',
    prompt: 'There ___ two books on the table.',
    options: ['is', 'am', 'are', 'be'],
    correctIndex: 2,
  },
  {
    id: 'gr-a1-04',
    level: 'A1',
    category: 'grammar',
    prompt: "I ___ a doctor. I am a teacher.",
    options: ['am not', "isn't", "aren't", 'not am'],
    correctIndex: 0,
  },
  // A2
  {
    id: 'gr-a2-01',
    level: 'A2',
    category: 'grammar',
    prompt: 'Yesterday, we ___ to the cinema.',
    options: ['go', 'goes', 'went', 'going'],
    correctIndex: 2,
  },
  {
    id: 'gr-a2-02',
    level: 'A2',
    category: 'grammar',
    prompt: 'This book is ___ than that one.',
    options: ['interesting', 'more interesting', 'most interesting', 'interestinger'],
    correctIndex: 1,
  },
  {
    id: 'gr-a2-03',
    level: 'A2',
    category: 'grammar',
    prompt: 'We ___ going to visit Paris next summer.',
    options: ['am', 'is', 'are', 'be'],
    correctIndex: 2,
  },
  {
    id: 'gr-a2-04',
    level: 'A2',
    category: 'grammar',
    prompt: "There isn't ___ milk in the fridge.",
    options: ['some', 'any', 'a', 'many'],
    correctIndex: 1,
  },
  // B1
  {
    id: 'gr-b1-01',
    level: 'B1',
    category: 'grammar',
    prompt: 'I have never ___ to Japan.',
    options: ['go', 'went', 'gone', 'going'],
    correctIndex: 2,
  },
  {
    id: 'gr-b1-02',
    level: 'B1',
    category: 'grammar',
    prompt: 'If it rains tomorrow, we ___ the picnic.',
    options: ['cancel', 'will cancel', 'would cancel', 'cancelled'],
    correctIndex: 1,
  },
  {
    id: 'gr-b1-03',
    level: 'B1',
    category: 'grammar',
    prompt: 'If I ___ more money, I would travel the world.',
    options: ['have', 'had', 'has', 'will have'],
    correctIndex: 1,
  },
  {
    id: 'gr-b1-04',
    level: 'B1',
    category: 'grammar',
    prompt: "You ___ wear a seatbelt in the car. It's the law.",
    options: ['can', 'might', 'must', 'could'],
    correctIndex: 2,
  },
  // B2
  {
    id: 'gr-b2-01',
    level: 'B2',
    category: 'grammar',
    prompt: 'The new bridge ___ next year.',
    options: ['will build', 'is building', 'will be built', 'was built'],
    correctIndex: 2,
  },
  {
    id: 'gr-b2-02',
    level: 'B2',
    category: 'grammar',
    prompt: 'She said she ___ tired.',
    options: ['is', 'has been', 'be', 'was'],
    correctIndex: 3,
  },
  {
    id: 'gr-b2-03',
    level: 'B2',
    category: 'grammar',
    prompt: 'If I had studied harder, I ___ the exam.',
    options: ['would pass', 'would have passed', 'had passed', 'will pass'],
    correctIndex: 1,
  },
  {
    id: 'gr-b2-04',
    level: 'B2',
    category: 'grammar',
    prompt: 'The man ___ car was stolen called the police.',
    options: ['who', 'which', 'whose', 'that'],
    correctIndex: 2,
  },
  // C1
  {
    id: 'gr-c1-01',
    level: 'C1',
    category: 'grammar',
    prompt: '___ I known you were coming, I would have cooked dinner.',
    options: ['If', 'Had', 'Should', 'Unless'],
    correctIndex: 1,
  },
  {
    id: 'gr-c1-02',
    level: 'C1',
    category: 'grammar',
    prompt: "If she hadn't missed the flight, she ___ jet-lagged now.",
    options: ['would have been', "wouldn't be", "isn't", "hadn't been"],
    correctIndex: 1,
  },
  {
    id: 'gr-c1-03',
    level: 'C1',
    category: 'grammar',
    prompt: 'It was John ___ broke the window, not Peter.',
    options: ['which', 'whom', 'who', 'whose'],
    correctIndex: 2,
  },
  {
    id: 'gr-c1-04',
    level: 'C1',
    category: 'grammar',
    prompt: 'You ___ locked the door — I already did it.',
    options: ["mustn't have", 'don\'t need to', "needn't have", "shouldn't"],
    correctIndex: 2,
  },
  // C2
  {
    id: 'gr-c2-01',
    level: 'C2',
    category: 'grammar',
    prompt: 'The committee insists that he ___ present at every meeting.',
    options: ['is', 'be', 'was', 'being'],
    correctIndex: 1,
  },
  {
    id: 'gr-c2-02',
    level: 'C2',
    category: 'grammar',
    prompt: '___ the circumstances, I think we made the right decision.',
    options: ['Despite', 'Given', 'Although', 'Whereas'],
    correctIndex: 1,
  },
  {
    id: 'gr-c2-03',
    level: 'C2',
    category: 'grammar',
    prompt: 'Were the plan to fail, we ___ have a backup ready.',
    options: ['should', 'would', 'will', 'shall'],
    correctIndex: 1,
  },
  {
    id: 'gr-c2-04',
    level: 'C2',
    category: 'grammar',
    prompt: "I couldn't care ___ about what they think.",
    options: ['more', 'much', 'less', 'little'],
    correctIndex: 2,
  },

  // ===== VOCABULARY =====
  // A1
  {
    id: 'vo-a1-01',
    level: 'A1',
    category: 'vocabulary',
    prompt: "What is the opposite of 'big'?",
    options: ['small', 'tall', 'long', 'wide'],
    correctIndex: 0,
  },
  {
    id: 'vo-a1-02',
    level: 'A1',
    category: 'vocabulary',
    prompt: 'Which word means a place where you sleep?',
    options: ['kitchen', 'bedroom', 'bathroom', 'garden'],
    correctIndex: 1,
  },
  {
    id: 'vo-a1-03',
    level: 'A1',
    category: 'vocabulary',
    prompt: "Choose the correct word: 'I drink ___ every morning.'",
    options: ['coffee', 'chair', 'book', 'window'],
    correctIndex: 0,
  },
  {
    id: 'vo-a1-04',
    level: 'A1',
    category: 'vocabulary',
    prompt: 'What do you call the meal you eat in the morning?',
    options: ['lunch', 'dinner', 'breakfast', 'snack'],
    correctIndex: 2,
  },
  // A2
  {
    id: 'vo-a2-01',
    level: 'A2',
    category: 'vocabulary',
    prompt: "Which word means 'not expensive'?",
    options: ['cheap', 'expensive', 'costly', 'priceless'],
    correctIndex: 0,
  },
  {
    id: 'vo-a2-02',
    level: 'A2',
    category: 'vocabulary',
    prompt: "What is a synonym for 'happy'?",
    options: ['sad', 'glad', 'angry', 'tired'],
    correctIndex: 1,
  },
  {
    id: 'vo-a2-03',
    level: 'A2',
    category: 'vocabulary',
    prompt: "Choose the word: 'The weather is very ___ today, take an umbrella.'",
    options: ['sunny', 'rainy', 'dry', 'hot'],
    correctIndex: 1,
  },
  {
    id: 'vo-a2-04',
    level: 'A2',
    category: 'vocabulary',
    prompt: 'What do you call a person who teaches students?',
    options: ['doctor', 'teacher', 'driver', 'lawyer'],
    correctIndex: 1,
  },
  // B1
  {
    id: 'vo-b1-01',
    level: 'B1',
    category: 'vocabulary',
    prompt: "What does 'to borrow' mean?",
    options: ['to give something away', 'to take something and return it later', 'to buy something', 'to lose something'],
    correctIndex: 1,
  },
  {
    id: 'vo-b1-02',
    level: 'B1',
    category: 'vocabulary',
    prompt: "Choose the correct synonym for 'difficult'.",
    options: ['easy', 'simple', 'challenging', 'boring'],
    correctIndex: 2,
  },
  {
    id: 'vo-b1-03',
    level: 'B1',
    category: 'vocabulary',
    prompt: "What is the meaning of 'to postpone'?",
    options: ['to cancel', 'to delay', 'to start', 'to finish'],
    correctIndex: 1,
  },
  {
    id: 'vo-b1-04',
    level: 'B1',
    category: 'vocabulary',
    prompt: "Which word means 'to introduce something new to the market'?",
    options: ['launch', 'retire', 'borrow', 'postpone'],
    correctIndex: 0,
  },
  // B2
  {
    id: 'vo-b2-01',
    level: 'B2',
    category: 'vocabulary',
    prompt: "What does 'reluctant' mean?",
    options: ['unwilling', 'eager', 'confident', 'curious'],
    correctIndex: 0,
  },
  {
    id: 'vo-b2-02',
    level: 'B2',
    category: 'vocabulary',
    prompt: "Choose the best synonym for 'substantial'.",
    options: ['tiny', 'considerable', 'fragile', 'temporary'],
    correctIndex: 1,
  },
  {
    id: 'vo-b2-03',
    level: 'B2',
    category: 'vocabulary',
    prompt: "What is the meaning of 'to overwhelm'?",
    options: ['to affect someone with too much of something', 'to relax someone completely', 'to ignore someone', 'to thank someone'],
    correctIndex: 0,
  },
  {
    id: 'vo-b2-04',
    level: 'B2',
    category: 'vocabulary',
    prompt: "Which word means 'happening or existing at the same time'?",
    options: ['subsequent', 'simultaneous', 'occasional', 'consecutive'],
    correctIndex: 1,
  },
  // C1
  {
    id: 'vo-c1-01',
    level: 'C1',
    category: 'vocabulary',
    prompt: "What does 'meticulous' mean?",
    options: ['careless', 'extremely careful and precise', 'lazy', 'quick'],
    correctIndex: 1,
  },
  {
    id: 'vo-c1-02',
    level: 'C1',
    category: 'vocabulary',
    prompt: "Choose the best synonym for 'ubiquitous'.",
    options: ['rare', 'everywhere', 'hidden', 'expensive'],
    correctIndex: 1,
  },
  {
    id: 'vo-c1-03',
    level: 'C1',
    category: 'vocabulary',
    prompt: "What is the meaning of 'to alleviate'?",
    options: ['to worsen', 'to reduce', 'to ignore', 'to create'],
    correctIndex: 1,
  },
  {
    id: 'vo-c1-04',
    level: 'C1',
    category: 'vocabulary',
    prompt: "Which word means 'a strong desire to do something'?",
    options: ['reluctance', 'apathy', 'zeal', 'indifference'],
    correctIndex: 2,
  },
  // C2
  {
    id: 'vo-c2-01',
    level: 'C2',
    category: 'vocabulary',
    prompt: "What does 'ephemeral' mean?",
    options: ['lasting forever', 'short-lived', 'extremely large', 'dangerous'],
    correctIndex: 1,
  },
  {
    id: 'vo-c2-02',
    level: 'C2',
    category: 'vocabulary',
    prompt: "Choose the best synonym for 'obfuscate'.",
    options: ['clarify', 'simplify', 'confuse', 'reveal'],
    correctIndex: 2,
  },
  {
    id: 'vo-c2-03',
    level: 'C2',
    category: 'vocabulary',
    prompt: "What is the meaning of 'sycophantic'?",
    options: ['honest', 'excessively flattering', 'indifferent', 'rebellious'],
    correctIndex: 1,
  },
  {
    id: 'vo-c2-04',
    level: 'C2',
    category: 'vocabulary',
    prompt: "Which word best describes someone who is 'inscrutable'?",
    options: ['easy to understand', 'impossible to interpret', 'very talkative', 'generous'],
    correctIndex: 1,
  },

  // ===== READING =====
  // A1
  {
    id: 're-a1-01',
    level: 'A1',
    category: 'reading',
    passage:
      'My name is Anna. I am ten years old. I live in a small house with my mother, father, and my cat, Tom. Every morning I eat breakfast and go to school. I like my school. My best friend is Lily. We play together after school.',
    prompt: "What is the name of Anna's cat?",
    options: ['Lily', 'Mother', 'Tom', 'Anna'],
    correctIndex: 2,
  },
  {
    id: 're-a1-02',
    level: 'A1',
    category: 'reading',
    passage:
      "Ben likes sports. He plays football on Mondays and swims on Wednesdays. On Saturdays, he rides his bike in the park with his sister. Ben's favorite sport is football because he can play with his friends. He is very happy on Saturdays.",
    prompt: 'What does Ben do on Wednesdays?',
    options: ['Rides his bike', 'Swims', 'Plays football', 'Rests'],
    correctIndex: 1,
  },
  {
    id: 're-a1-03',
    level: 'A1',
    category: 'reading',
    passage:
      "This is my family. My father is a cook. My mother is a nurse. I have one brother. His name is Sam. Sam is six. I am eight. We live in a flat in the city. We have a small dog. Its name is Max.",
    prompt: 'What is the name of the family dog?',
    options: ['Sam', 'Max', 'Anna', 'Tom'],
    correctIndex: 1,
  },
  {
    id: 're-a1-04',
    level: 'A1',
    category: 'reading',
    passage:
      "Today is Monday. Kate goes to work by bus. The bus stop is near her house. She works in a shop. The shop sells fruit and bread. Kate likes her job because she meets many people every day.",
    prompt: 'How does Kate get to work?',
    options: ['By car', 'By train', 'By bus', 'On foot'],
    correctIndex: 2,
  },
  // A2
  {
    id: 're-a2-01',
    level: 'A2',
    category: 'reading',
    passage:
      "Every weekend, Maria visits the farmers' market near her home. She likes to buy fresh fruit and vegetables there. Last Saturday, she bought apples, tomatoes, and a bunch of flowers for her kitchen table. The market opens at eight in the morning and closes at two in the afternoon. Maria always arrives early to get the best fruit.",
    prompt: 'What did Maria buy last Saturday?',
    options: ['Bread and milk', 'Only vegetables', 'A new table', 'Apples, tomatoes, and flowers'],
    correctIndex: 3,
  },
  {
    id: 're-a2-02',
    level: 'A2',
    category: 'reading',
    passage:
      "Last month, Tom went on a trip to the mountains with his family. They stayed in a small cabin near a lake. Every day, they went hiking and fishing. In the evenings, they cooked dinner over a campfire and told stories. Tom loved the fresh air and the quiet forest, and he wants to go back next year.",
    prompt: "Where did Tom's family stay?",
    options: ['In a city apartment', 'In a tent', 'In a small cabin', 'In a hotel'],
    correctIndex: 2,
  },
  {
    id: 're-a2-03',
    level: 'A2',
    category: 'reading',
    passage:
      "Sofia is learning to cook. Every Sunday, her grandmother teaches her a new recipe. Last week, they made a vegetable soup together. Sofia chopped the carrots and onions while her grandmother added the spices. They ate the soup for dinner, and Sofia's father said it was delicious. Now Sofia wants to learn how to bake bread next.",
    prompt: 'Who teaches Sofia to cook?',
    options: ['Her father', 'Her grandmother', 'A chef', 'Her friend'],
    correctIndex: 1,
  },
  {
    id: 're-a2-04',
    level: 'A2',
    category: 'reading',
    passage:
      "Daniel works in an office in the city center. He usually starts work at nine and finishes at five. On Fridays, his team has a short meeting to talk about the week. After work, Daniel often goes to the gym before going home. On weekends, he likes to relax and watch films with his wife.",
    prompt: "What does Daniel often do after work?",
    options: ['Go to the gym', 'Go shopping', 'Visit friends', 'Cook dinner'],
    correctIndex: 0,
  },
  // B1
  {
    id: 're-b1-01',
    level: 'B1',
    category: 'reading',
    passage:
      "Working from home has become common for many employees since the pandemic. While some people enjoy the flexibility of setting their own schedule, others find it hard to separate work from personal life. Experts suggest creating a dedicated workspace and sticking to regular hours to stay productive. Companies are now offering hybrid options, allowing staff to split their time between the office and home.",
    prompt: 'According to the passage, what do experts recommend for people working from home?',
    options: ['Working late every night', 'Avoiding the office completely', 'Changing jobs frequently', 'Creating a dedicated workspace and regular hours'],
    correctIndex: 3,
  },
  {
    id: 're-b1-02',
    level: 'B1',
    category: 'reading',
    passage:
      "Recycling has become an important part of daily life in many countries. Households are encouraged to separate paper, plastic, and glass before collection. Although recycling helps reduce waste, some critics argue that not all materials are actually processed properly. Local governments are now investing in better facilities to make sure recycled materials are used effectively rather than sent to landfills.",
    prompt: 'What concern do critics raise about recycling, according to the passage?',
    options: ['Not all materials are properly processed', 'It is too expensive', "People don't want to recycle", 'It creates more waste'],
    correctIndex: 0,
  },
  {
    id: 're-b1-03',
    level: 'B1',
    category: 'reading',
    passage:
      "Many young people today choose to travel for a year before starting university or a career. This is often called a 'gap year'. Supporters say it helps people gain independence, learn new skills, and understand different cultures. Critics, however, worry that some students lose motivation to study afterward, or that a gap year is only possible for those with enough money to travel comfortably.",
    prompt: 'What worry do critics have about gap years, according to the passage?',
    options: ['They are too short', 'Students may lose motivation to study', 'They are illegal in some countries', 'They always cost nothing'],
    correctIndex: 1,
  },
  {
    id: 're-b1-04',
    level: 'B1',
    category: 'reading',
    passage:
      "Public libraries are changing to keep up with modern life. Instead of only lending books, many now offer free internet access, printing services, and even spaces for community events. Some libraries run classes on computer skills for older visitors who did not grow up using technology. Librarians say these changes help bring more people, especially younger generations, back through the doors.",
    prompt: 'According to the passage, why do some libraries run computer classes?',
    options: ['To replace all books with computers', 'To help older visitors learn technology skills', 'To reduce the number of visitors', 'To close down old libraries'],
    correctIndex: 1,
  },
  // B2
  {
    id: 're-b2-01',
    level: 'B2',
    category: 'reading',
    passage:
      "The rise of remote work has fundamentally altered how companies approach office space. Many organizations, having realized that productivity does not necessarily depend on physical presence, have downsized their headquarters or adopted flexible desk arrangements. This shift, however, has sparked debate about workplace culture: while some employees thrive without daily commutes, others report feeling isolated and disconnected from their colleagues, raising questions about the long-term effects on collaboration and mental well-being.",
    prompt: 'According to the passage, what is one downside of remote work mentioned by some employees?',
    options: ['Higher salaries', 'Longer commutes', 'Feelings of isolation', 'Increased office space'],
    correctIndex: 2,
  },
  {
    id: 're-b2-02',
    level: 'B2',
    category: 'reading',
    passage:
      "Urban beekeeping has grown in popularity as city dwellers seek ways to support declining bee populations and connect with nature. Rooftops and community gardens across major cities now host hives, producing honey while pollinating local plants. Despite its benefits, some experts warn that poorly managed urban hives can spread disease among bee colonies, and they urge new beekeepers to receive proper training before starting this increasingly trendy hobby.",
    prompt: 'What warning do experts give about urban beekeeping?',
    options: ['It is illegal in most cities', 'Bees cannot survive in cities', 'Honey production has stopped', 'Poorly managed hives can spread disease'],
    correctIndex: 3,
  },
  {
    id: 're-b2-03',
    level: 'B2',
    category: 'reading',
    passage:
      "As streaming services compete for subscribers, many have begun investing heavily in original content rather than licensing shows from other studios. This strategy allows platforms to differentiate themselves and retain exclusive rights, but it comes at a significant financial risk: a single unsuccessful series can cost tens of millions of dollars. Industry analysts note that only companies with substantial cash reserves can sustain this approach over the long term.",
    prompt: 'What risk of producing original content does the passage mention?',
    options: ['Losing exclusive rights', 'High cost of unsuccessful series', 'Fewer subscribers overall', 'Legal disputes with studios'],
    correctIndex: 1,
  },
  {
    id: 're-b2-04',
    level: 'B2',
    category: 'reading',
    passage:
      "Noise pollution in cities is often overlooked compared to other environmental issues, yet research increasingly links it to health problems such as elevated stress and disrupted sleep. Urban planners are now experimenting with solutions including quieter road surfaces, sound-absorbing barriers along highways, and stricter limits on construction noise during early morning hours. Some residents, though, argue that these measures are implemented too slowly to make a real difference.",
    prompt: 'What health effects does the passage link to noise pollution?',
    options: ['Improved sleep quality', 'Elevated stress and disrupted sleep', 'Better concentration', 'Reduced traffic accidents'],
    correctIndex: 1,
  },
  // C1
  {
    id: 're-c1-01',
    level: 'C1',
    category: 'reading',
    passage:
      "Despite decades of research, the precise mechanisms underlying human memory consolidation remain the subject of considerable scientific debate. Some neuroscientists contend that sleep plays an indispensable role, arguing that specific stages of rest allow the brain to transfer information from short-term to long-term storage. Others, however, caution against overstating sleep's importance, pointing to case studies of individuals with severe sleep disorders who nonetheless retain the capacity to form durable memories, suggesting that consolidation may rely on a more distributed set of neural processes.",
    prompt: 'What position do the neuroscientists mentioned second in the passage hold?',
    options: ['Sleep is the only factor in memory', 'Memory disorders are caused by sleep', 'Consolidation may depend on multiple neural processes', 'Long-term memory does not exist'],
    correctIndex: 2,
  },
  {
    id: 're-c1-02',
    level: 'C1',
    category: 'reading',
    passage:
      "The phenomenon of 'greenwashing'—wherein companies exaggerate or fabricate the environmental benefits of their products—has drawn increasing scrutiny from regulators and consumer advocacy groups alike. Critics argue that vague or unsubstantiated claims, such as labeling a product 'eco-friendly' without independent verification, mislead consumers who genuinely wish to reduce their environmental footprint. In response, several jurisdictions have begun drafting legislation that would require companies to substantiate any environmental marketing claims with verifiable data, though enforcement remains inconsistent across regions.",
    prompt: 'Why are regulators drafting new legislation, according to the passage?',
    options: ['To require companies to substantiate green claims with data', 'To ban all environmental marketing', 'To increase product prices', 'To promote greenwashing'],
    correctIndex: 0,
  },
  {
    id: 're-c1-03',
    level: 'C1',
    category: 'reading',
    passage:
      "Automation is often discussed in terms of job losses, yet economic historians point out that previous waves of technological disruption, from mechanized agriculture to computerization, ultimately generated more employment than they eliminated, albeit in different sectors and often requiring substantial retraining. Whether artificial intelligence follows this same trajectory remains contested: some economists argue that the pace and breadth of current automation are qualitatively different from past transitions, leaving workers with far less time to adapt.",
    prompt: 'What do some economists argue is different about the current wave of automation?',
    options: ['It affects only agriculture', 'Its pace and breadth leave workers less time to adapt', 'It has already reduced unemployment', 'It requires no retraining at all'],
    correctIndex: 1,
  },
  {
    id: 're-c1-04',
    level: 'C1',
    category: 'reading',
    passage:
      "The placebo effect—whereby patients experience genuine physiological improvement after receiving a treatment with no active therapeutic ingredient—continues to puzzle researchers, who increasingly view it not as mere self-deception but as a measurable neurobiological response tied to expectation and context. Intriguingly, recent studies have shown that placebos can produce measurable benefits even when patients are explicitly told they are receiving an inactive substance, suggesting that the ritual of treatment itself carries therapeutic weight independent of conscious belief.",
    prompt: 'What surprising finding about placebos does the passage describe?',
    options: ['Placebos never work without deception', 'Placebos can work even when patients know they are inactive', 'Placebos only work on children', 'Placebos have been banned in research'],
    correctIndex: 1,
  },
  // C2
  {
    id: 're-c2-01',
    level: 'C2',
    category: 'reading',
    passage:
      "The notion that language merely reflects pre-existing thought has been persistently challenged by proponents of linguistic relativity, who argue instead that the very categories through which we perceive reality are, to a significant extent, shaped by the grammatical and lexical structures of our native tongue. While the strongest formulations of this hypothesis—suggesting that speakers of different languages inhabit fundamentally incommensurable conceptual worlds—have largely fallen out of favor, more moderate versions continue to find empirical support in studies examining color perception, spatial reasoning, and the categorization of time.",
    prompt: "What does the passage suggest about the 'strongest formulations' of linguistic relativity?",
    options: ['They focus only on color perception', 'They are now widely accepted', 'They have largely fallen out of favor', 'They were never proposed'],
    correctIndex: 2,
  },
  {
    id: 're-c2-02',
    level: 'C2',
    category: 'reading',
    passage:
      "Bureaucratic inertia, that seemingly ineradicable tendency of institutions to perpetuate established procedures long after their original rationale has evaporated, is often attributed to risk aversion among administrators reluctant to be held accountable for deviating from precedent. Yet a growing body of organizational research suggests a subtler culprit: the diffusion of responsibility across layers of hierarchy renders any single individual's incentive to challenge the status quo vanishingly small, such that reform, however self-evidently beneficial, requires a degree of coordinated will that most institutions structurally fail to muster.",
    prompt: 'According to the passage, what does recent organizational research suggest is a cause of bureaucratic inertia?',
    options: ['Excessive reform efforts', 'Diffusion of responsibility across hierarchy', 'Lack of funding', 'Individual incompetence'],
    correctIndex: 1,
  },
  {
    id: 're-c2-03',
    level: 'C2',
    category: 'reading',
    passage:
      "The tendency of expert forecasters to overestimate their own predictive accuracy, well documented across domains ranging from geopolitics to finance, has been attributed by some psychologists to a form of motivated reasoning: the professional incentives attached to appearing authoritative militate against the public acknowledgment of uncertainty. Others contend that the phenomenon is less a matter of self-interest than of a deeper cognitive bias, whereby the very expertise that lends credibility to a forecast also narrows the range of scenarios an expert is willing to entertain.",
    prompt: 'According to the passage, what do some psychologists attribute forecaster overconfidence to?',
    options: ['A lack of professional training', 'Motivated reasoning tied to professional incentives', 'Random chance', 'Insufficient access to data'],
    correctIndex: 1,
  },
  {
    id: 're-c2-04',
    level: 'C2',
    category: 'reading',
    passage:
      "Contrary to the popular assumption that irony is a purely modern, self-aware rhetorical mode, classical scholars have traced its deployment—often in strikingly similar forms—back to antiquity, where orators used feigned ignorance to expose an interlocutor's faulty reasoning. What distinguishes contemporary irony, some argue, is not its underlying mechanism but the sheer pervasiveness of mediated communication, which has multiplied the contexts in which ironic statements can be misread as sincere, thereby raising the interpretive stakes of a rhetorical device once confined largely to face-to-face exchange.",
    prompt: 'What do some argue distinguishes contemporary irony from its classical form?',
    options: ['Irony did not exist in antiquity', 'The pervasiveness of mediated communication raises the risk of misreading', 'Modern audiences never misunderstand irony', 'Classical orators never used irony'],
    correctIndex: 1,
  },

  // ===== USAGE =====
  // A1
  {
    id: 'us-a1-01',
    level: 'A1',
    category: 'usage',
    prompt: 'I usually get up ___ 7 o\'clock.',
    options: ['in', 'on', 'at', 'by'],
    correctIndex: 2,
  },
  {
    id: 'us-a1-02',
    level: 'A1',
    category: 'usage',
    prompt: 'She is good ___ maths.',
    options: ['at', 'in', 'on', 'for'],
    correctIndex: 0,
  },
  {
    id: 'us-a1-03',
    level: 'A1',
    category: 'usage',
    prompt: "Turn ___ the light, please, it's dark.",
    options: ['off', 'on', 'up', 'out'],
    correctIndex: 1,
  },
  {
    id: 'us-a1-04',
    level: 'A1',
    category: 'usage',
    prompt: 'Can you help me, ___?',
    options: ['please', 'now', 'quick', 'fast'],
    correctIndex: 0,
  },
  // A2
  {
    id: 'us-a2-01',
    level: 'A2',
    category: 'usage',
    prompt: 'Could you please hand ___ your homework?',
    options: ['on', 'in', 'up', 'off'],
    correctIndex: 1,
  },
  {
    id: 'us-a2-02',
    level: 'A2',
    category: 'usage',
    prompt: "I'm looking ___ my keys. Have you seen them?",
    options: ['for', 'at', 'after', 'up'],
    correctIndex: 0,
  },
  {
    id: 'us-a2-03',
    level: 'A2',
    category: 'usage',
    prompt: 'We need to get ___ the bus at the next stop.',
    options: ['on', 'up', 'off', 'in'],
    correctIndex: 2,
  },
  {
    id: 'us-a2-04',
    level: 'A2',
    category: 'usage',
    prompt: "It's important to arrive ___ time for the meeting.",
    options: ['in', 'at', 'by', 'on'],
    correctIndex: 3,
  },
  // B1
  {
    id: 'us-b1-01',
    level: 'B1',
    category: 'usage',
    prompt: 'She decided to give ___ smoking last year.',
    options: ['in', 'up', 'out', 'off'],
    correctIndex: 1,
  },
  {
    id: 'us-b1-02',
    level: 'B1',
    category: 'usage',
    prompt: "He's very good ___ dealing with difficult customers.",
    options: ['in', 'for', 'at', 'with'],
    correctIndex: 2,
  },
  {
    id: 'us-b1-03',
    level: 'B1',
    category: 'usage',
    prompt: 'I am afraid I have to turn ___ your invitation.',
    options: ['off', 'down', 'up', 'over'],
    correctIndex: 1,
  },
  {
    id: 'us-b1-04',
    level: 'B1',
    category: 'usage',
    prompt: "Could you keep an eye ___ my bag while I'm away?",
    options: ['at', 'for', 'on', 'in'],
    correctIndex: 2,
  },
  // B2
  {
    id: 'us-b2-01',
    level: 'B2',
    category: 'usage',
    prompt: 'The company had to lay ___ hundreds of workers during the recession.',
    options: ['down', 'off', 'out', 'up'],
    correctIndex: 1,
  },
  {
    id: 'us-b2-02',
    level: 'B2',
    category: 'usage',
    prompt: "He tends to come ___ as arrogant, even though he's actually quite shy.",
    options: ['up', 'across', 'over', 'through'],
    correctIndex: 1,
  },
  {
    id: 'us-b2-03',
    level: 'B2',
    category: 'usage',
    prompt: 'Choose the more formal option for a rejection email.',
    options: [
      'We regret to inform you that your application was not successful.',
      "Gonna need to pass on this one.",
      "What's up with this application?",
      'We got turned down on this one.',
    ],
    correctIndex: 0,
  },
  {
    id: 'us-b2-04',
    level: 'B2',
    category: 'usage',
    prompt: "She's been putting ___ her dentist appointment for weeks.",
    options: ['up', 'down', 'off', 'out'],
    correctIndex: 2,
  },
  // C1
  {
    id: 'us-c1-01',
    level: 'C1',
    category: 'usage',
    prompt: 'The negotiations broke ___ after both sides failed to compromise.',
    options: ['down', 'off', 'up', 'out'],
    correctIndex: 0,
  },
  {
    id: 'us-c1-02',
    level: 'C1',
    category: 'usage',
    prompt: 'Which sentence is most appropriate in a formal business email?',
    options: [
      'Hey, just checking in about this.',
      'I am writing to follow up on our previous conversation.',
      "What's up with this?",
      'Gonna need an answer soon.',
    ],
    correctIndex: 1,
  },
  {
    id: 'us-c1-03',
    level: 'C1',
    category: 'usage',
    prompt: 'He is known for his ability to ___ complex ideas into simple terms.',
    options: ['dissolve', 'dilute', 'distill', 'disperse'],
    correctIndex: 2,
  },
  {
    id: 'us-c1-04',
    level: 'C1',
    category: 'usage',
    prompt: 'The two companies finally decided to ___ forces to compete with larger rivals.',
    options: ['combine', 'join', 'merge', 'unite'],
    correctIndex: 1,
  },
  // C2
  {
    id: 'us-c2-01',
    level: 'C2',
    category: 'usage',
    prompt: 'Her speech was carefully worded to ___ any direct criticism of the government.',
    options: ['sideline', 'sidestep', 'sideswipe', 'sidewalk'],
    correctIndex: 1,
  },
  {
    id: 'us-c2-02',
    level: 'C2',
    category: 'usage',
    prompt: 'Which phrase would a native speaker most likely use to politely disagree in a meeting?',
    options: [
      "You're wrong.",
      "I see your point, but I'm not sure that fully accounts for...",
      'No way.',
      "That's a bad idea.",
    ],
    correctIndex: 1,
  },
  {
    id: 'us-c2-03',
    level: 'C2',
    category: 'usage',
    prompt: "The critic's review was so scathing that the director felt compelled to ___ publicly.",
    options: ['weigh in', 'back down', 'hit back', 'own up'],
    correctIndex: 2,
  },
  {
    id: 'us-c2-04',
    level: 'C2',
    category: 'usage',
    prompt: "Choose the idiom that means 'to discuss a sensitive topic carefully, without addressing it directly.'",
    options: ['beat around the bush', 'jump the gun', 'tread carefully', 'spill the beans'],
    correctIndex: 0,
  },
];
